export const EVENTS_TYPES = {
  // CREATE_USER_GAMIFICATION: 'CREATE_USER_GAMIFICATION',
  PROGRESS_EVENTS: 'PROGRESS_EVENTS',
  MANY_PROGRESS_EVENTS: 'MANY_PROGRESS_EVENTS',
  MESSAGE_MANY_CANDIDATE_EVENTS: 'MESSAGE_MANY_CANDIDATE_EVENTS',
};
